//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MouseMasterVR.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeUse {
            get {
                return ((bool)(this["FirstTimeUse"]));
            }
            set {
                this["FirstTimeUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double WindowPosTop {
            get {
                return ((double)(this["WindowPosTop"]));
            }
            set {
                this["WindowPosTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double WindowPosLeft {
            get {
                return ((double)(this["WindowPosLeft"]));
            }
            set {
                this["WindowPosLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainPowerSwitch {
            get {
                return ((bool)(this["MainPowerSwitch"]));
            }
            set {
                this["MainPowerSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UpdateModeDial {
            get {
                return ((int)(this["UpdateModeDial"]));
            }
            set {
                this["UpdateModeDial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Falcon BMS")]
        public string GameTargetName {
            get {
                return ((string)(this["GameTargetName"]));
            }
            set {
                this["GameTargetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press Any Key")]
        public string MouseUpRebind {
            get {
                return ((string)(this["MouseUpRebind"]));
            }
            set {
                this["MouseUpRebind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press Any Key")]
        public string MouseDownRebind {
            get {
                return ((string)(this["MouseDownRebind"]));
            }
            set {
                this["MouseDownRebind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press Any Button")]
        public string MouseLeftClickRebind {
            get {
                return ((string)(this["MouseLeftClickRebind"]));
            }
            set {
                this["MouseLeftClickRebind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Press Any Button")]
        public string MouseRightClickRebind {
            get {
                return ((string)(this["MouseRightClickRebind"]));
            }
            set {
                this["MouseRightClickRebind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2323")]
        public int MouseLeftRebindKey {
            get {
                return ((int)(this["MouseLeftRebindKey"]));
            }
            set {
                this["MouseLeftRebindKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2323")]
        public int MouseRightRebindKey {
            get {
                return ((int)(this["MouseRightRebindKey"]));
            }
            set {
                this["MouseRightRebindKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GettingLeftRebindKey {
            get {
                return ((bool)(this["GettingLeftRebindKey"]));
            }
            set {
                this["GettingLeftRebindKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GettingRightRebindKey {
            get {
                return ((bool)(this["GettingRightRebindKey"]));
            }
            set {
                this["GettingRightRebindKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JoystickIsPolling {
            get {
                return ((bool)(this["JoystickIsPolling"]));
            }
            set {
                this["JoystickIsPolling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppUpdated {
            get {
                return ((bool)(this["AppUpdated"]));
            }
            set {
                this["AppUpdated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppUpdating {
            get {
                return ((bool)(this["AppUpdating"]));
            }
            set {
                this["AppUpdating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string UpdateFileTarget {
            get {
                return ((string)(this["UpdateFileTarget"]));
            }
            set {
                this["UpdateFileTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string UpdatePackagePath {
            get {
                return ((string)(this["UpdatePackagePath"]));
            }
            set {
                this["UpdatePackagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MouseDebounce {
            get {
                return ((double)(this["MouseDebounce"]));
            }
            set {
                this["MouseDebounce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MouseMaster")]
        public string AppTitle {
            get {
                return ((string)(this["AppTitle"]));
            }
            set {
                this["AppTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://veterans-gaming.com/semlerpdx/vglabs/apps/changelog_mousemastervr.html")]
        public string AppChangelog {
            get {
                return ((string)(this["AppChangelog"]));
            }
            set {
                this["AppChangelog"] = value;
            }
        }
    }
}
